[target]

# Include source files.
includes = ["src"]

# Exclude source files.
excludes = ["vendor", "spec"]

[report]
reportDirectory = "./tmp"

[report.coverageBounds]
satisfactory = 80.0
critical = 50.0

[reporter]

# TextReporter
[reporter.text]

# LcovReporter
[reporter.lcov]
fileName = "report.lcov"

# ProcessingTimeReporter
[reporter.processingTime]
